app.py
from flask import Flask
from views import views

app = Flask(__name__)
app.register_blueprint(views, url_prefix="/")

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=80, debug=True)

views.py
from flask import Blueprint, render_template, request, jsonify, send_file
import subprocess
import re
import requests
import hashlib
import pymysql

views = Blueprint("views", __name__)

#MySQL Configuration
# views.config['MYSQL_HOST'] = 'localhost'
# views.config['MYSQL_USER'] = 'root'
# views.config['MYSQL_PASSWORD'] = ''
# views.config['MYSQL_DB'] = 'college'

@views.route('/')
def index():
    return render_template("index.html")

@views.route('/about')
def about():
    return render_template("about.html")

@views.route('/service')
def service():
    return render_template("service.html")

@views.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        # Get form data
        name = request.form['name']
        email = request.form['email']
        subject = request.form['subject']
        message = request.form['message']
        
        # Insert into MySQL database
        conn = pymysql.connect(host='localhost', user='root', password='ubuntu', database='college')
        cursor = conn.cursor()
        sql_query = "INSERT INTO sentinel (name, email, subject, message) VALUES (%s, %s, %s, %s)"
        cursor.execute(sql_query, (name, email, subject, message))
        conn.commit()
        conn.close()
        
        return '<script>alert("Thank you! Your Message has been sent successfuly"); window.location.href="/contact";</script>'
    
    else:
        return render_template("contact.html")

@views.route('/policy')
def policy():
    return render_template("policy.html")

@views.route('/terms')
def terms():
    return render_template("terms.html")

@views.route('/service/port-scanner')
def portScanner():
    return render_template("port-scanner.html")

@views.route('/service/malware-scanner')
def malwareScanner():
    return render_template("malware-scanner.html")

@views.route('/service/volatile-vm')
def volatileVM():
    return render_template("volatile-vm.html")

@views.route('/service/volatile-vm/download')
def download_file():
    file_path = '/home/ubuntu/Server/VolatileVM/VolatileVM.rar'
    return send_file(file_path, as_attachment=True)

@views.route('/service/vulnerability-scanner')
def vulnerabilityScanner():
    return render_template("vulnerability-scanner.html")

@views.route('/results/port-scan', methods=['POST'])
def scanPorts():
    target = request.form.get('target')
    port_range = request.form.get('portRange')

    ip_regex = r'^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
    url_regex = r'^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$'


    if not target or not port_range or (not re.match(ip_regex, target) and not re.match(url_regex, target)):
        return "Error: Invalid target or port range", 400


    # Determine nmap arguments based on port range
    if port_range == 'all':
        ports = '-p-'
    else:  # Assume 'common'
        ports = '-p20,21,22,23,25,53,80,110,443'

    # Run nmap and capture its output
    result = subprocess.run(f'nmap -sC -sV {ports} -oX /home/ubuntu/Results/result.xml --stylesheet /home/ubuntu/Results/nmap-bootstrap.xsl {target}', shell=True, text=True, capture_output=True)
    subprocess.run(['xsltproc -o /home/ubuntu/Project/templates/results/result.html /home/ubuntu/Results/nmap-bootstrap.xsl /home/ubuntu/Results/result.xml'], shell=True)

    return render_template('/results/result.html')

@views.route('/api/scan', methods=['POST'])
def scan_file():
    # Get the uploaded file
    uploaded_file = request.files['file']
    
    if not uploaded_file:
        return jsonify({'error': 'No file uploaded'}), 400
    
    # VirusTotal API key
    api_key = '317d90e8d30b27cf62ca84a905f03f25f4848509df132b8dfaa15d9cbb7135b4'
    scan_url = 'https://www.virustotal.com/api/v3/'
    
    # Prepare headers with the API key
    headers = {
        'x-apikey': api_key
    }
    
    # Prepare the file data
    files = {
        'file': (uploaded_file.filename, uploaded_file.stream)
    }
    
    try:
        response = requests.post(scan_url + "files", files=files, headers=headers)
        
        if response.status_code == 200:
            sha256_hash = hashlib.sha256()
            uploaded_file.stream.seek(0)
            for chunk in iter(lambda: uploaded_file.stream.read(4096), b""):
                sha256_hash.update(chunk)
            sha256 = sha256_hash.hexdigest()

            return jsonify({'url' : f"https://www.virustotal.com/ui/file_behaviours/{sha256}_Zenbox/html"})
        
        else:
            return jsonify({'error': 'Failed to upload file to VirusTotal'}), response.status_code
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>CyberFort - Your Ultimate Cyber Fortress</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <link href="{{ url_for('static', filename='img/fevicon.png') }}" rel="icon" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500&family=Jost:wght@500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/lightbox/css/lightbox.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/317fe3b535.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-grow text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Navbar & Hero Start -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
                <a href="{{ url_for('views.index') }}" class="navbar-brand p-0">
                    <h1 class="m-0">CyberFort</h1>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav mx-auto py-0">
                        <a href="{{ url_for('views.index') }}" class="nav-item nav-link">Home</a>
                        <a href="{{ url_for('views.about') }}" class="nav-item nav-link">About</a>
                        <a href="{{ url_for('views.service') }}" class="nav-item nav-link">Service</a>
                        <a href="{{ url_for('views.contact') }}" class="nav-item nav-link active">Contact</a>
                    </div>
                </div>
            </nav>
            <div class="container-xxl py-5 bg-primary hero-header">
                <div class="container my-5 py-5 px-lg-5">
                    <div class="row g-5 py-5">
                        <div class="col-12 text-center">
                            <h1 class="text-white animated slideInDown">Contact</h1>
                            <hr class="bg-white mx-auto mt-0" style="width: 90px;">
                            <nav aria-label="breadcrumb">
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Navbar & Hero End -->
        <!-- Contact Start -->
        <form id="contactForm" method="POST" action="{{ url_for('views.contact') }}">
            <input type="hidden" name="access_key" value="7b11ea95-3005-4708-8952-29b1d165131d">
            <div class="container-xxl py-5">
                <div class="container py-5 px-lg-5">
                    <div class="wow fadeInUp" data-wow-delay="0.1s">
                        <p class="section-title text-secondary justify-content-center"><span></span>Contact Us<span></span></p>
                        <h1 class="text-center mb-5">Contact For Any Query</h1>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <div class="wow fadeInUp" data-wow-delay="0.3s">
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="name" id="name" placeholder="Your Name">
                                            <label for="name">Your Name</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input type="email" class="form-control" name="email" id="email" placeholder="Your Email">
                                            <label for="email">Your Email</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject">
                                            <label for="subject">Subject</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <textarea class="form-control" placeholder="Leave a message here" name="message" id="message" style="height: 150px"></textarea>
                                            <label for="message">Message</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!-- Contact End -->
        <!-- Footer Start -->
        <div class="container-fluid bg-primary text-light footer wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5 px-lg-5">
                <div class="row g-5">
                    <div class="col-md-6 col-lg-3">
                        <p class="section-title text-white h5 mb-4">Quick Link<span></span></p>
                        <a class="btn btn-link" href="{{ url_for('views.about') }}">About Us</a>
                        <a class="btn btn-link" href="{{ url_for('views.contact') }}">Contact Us</a>
                        <a class="btn btn-link" href="{{ url_for('views.policy') }}">Privacy Policy</a>
                        <a class="btn btn-link" href="{{ url_for('views.terms') }}">Terms & Condition</a>
                    </div>
                </div>
            </div>
            <div class="container px-lg-5">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="{{ url_for('views.index') }}">CyberFort</a>, All Rights Reserved.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-secondary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/counterup/counterup.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/isotope/isotope.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/lightbox/js/lightbox.min.js') }}"></script>
    <!-- Template Javascript -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

templates/service.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">

    <title>CyberFort - Your Ultimate Cyber Fortress</title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta content="" name="keywords">

    <meta content="" name="description">



   

    <link href="{{ url_for('static', filename='img/fevicon.png') }}" rel="icon" type="image/x-icon">



    

    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500&family=Jost:wght@500;600;700&display=swap" rel="stylesheet"> 



    

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">



   

    <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">

    <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">

    <link href="{{ url_for('static', filename='lib/lightbox/css/lightbox.min.css') }}" rel="stylesheet">



    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">



   

    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    <script src="https://kit.fontawesome.com/317fe3b535.js" crossorigin="anonymous"></script>

</head>



<body>

    <div class="container-xxl bg-white p-0">

        <!-- Spinner Start -->

        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">

            <div class="spinner-grow text-primary" style="width: 3rem; height: 3rem;" role="status">

                <span class="sr-only">Loading...</span>

            </div>

        </div>

        <!-- Spinner End -->





        <!-- Navbar & Hero Start -->

        <div class="container-xxl position-relative p-0">

            <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">

                <a href="{{ url_for('views.index') }}" class="navbar-brand p-0">

                    <h1 class="m-0">CyberFort</h1>

                    

                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">

                    <span class="fa fa-bars"></span>

                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">

                    <div class="navbar-nav mx-auto py-0">

                        <a href="{{ url_for('views.index') }}" class="nav-item nav-link">Home</a>

                        <a href="{{ url_for('views.about') }}" class="nav-item nav-link">About</a>

                        <a href="{{ url_for('views.service') }}" class="nav-item nav-link active">Service</a>

                        

                        <a href="{{ url_for('views.contact') }}" class="nav-item nav-link">Contact</a>

                    </div>

                    

                </div>

            </nav>



            <div class="container-xxl py-5 bg-primary hero-header">

                <div class="container my-5 py-5 px-lg-5">

                    <div class="row g-5 py-5">

                        <div class="col-12 text-center">

                            <h1 class="text-white animated slideInDown">Service</h1>

                            <hr class="bg-white mx-auto mt-0" style="width: 90px;">

                            <nav aria-label="breadcrumb">

                                

                            </nav>

                        </div>

                    </div>

                </div>

            </div>

        </div>

        <!-- Navbar & Hero End -->





        <!-- Service Start -->

        <div class="container-xxl py-5">

            <div class="container py-5 px-lg-5">

                <div class="wow fadeInUp" data-wow-delay="0.1s">

                    <p class="section-title text-secondary justify-content-center"><span></span>Our Services<span></span></p>

                    <h1 class="text-center mb-5">What Solutions We Provide</h1>

                </div>

                <div class="row g-4">

                    <div class="col-lg-4 col-md-4 wow fadeInUp" data-wow-delay="0.1s">

                        <div class="service-item d-flex flex-column text-center rounded">

                            <div class="service-icon flex-shrink-0">

                                <i class="fa-brands fa-searchengin fa-2x  "></i>

                            </div>

                            <h5 class="mb-3">Malware Scanner</h5>

                            <p class="m-0">A web-based tool that allow's users to scan files for the presence of malware, viruses, and other malicious software. </p>

                            <a class="btn btn-square" href="{{ url_for('views.malwareScanner') }}"><i class="fa fa-arrow-right"></i></a>

                        </div>

                    </div>

                    <div class="col-lg-4 col-md-4 wow fadeInUp" data-wow-delay="0.3s">

                        <div class="service-item d-flex flex-column text-center rounded">

                            <div class="service-icon flex-shrink-0">

                                <i class="fa-solid fa-file-shield fa-2x"></i>

                            </div>

                            <h5 class="mb-3">Volatile VM</h5>

                            <p class="m-0">A proprietary software that aspires to protect the end user from foreign threats and harmful exploitation of their product using the concept of virtualization. 

                            </p>

                            <a class="btn btn-square" href="{{ url_for('views.volatileVM') }}"><i class="fa fa-arrow-right"></i></a>

                        </div>

                    </div>

                    <div class="col-lg-4 col-md-4 wow fadeInUp" data-wow-delay="0.5s">

                        <div class="service-item d-flex flex-column text-center rounded">

                            <div class="service-icon flex-shrink-0">

                                <i class="fa-solid fa-ethernet fa-2x"></i>

                            </div>

                            <h5 class="mb-3">Port Scanner</h5>

                            <p class="m-0">A software tool designed to scan a computer system, network, or server for open ports. </p>

                            <a class="btn btn-square" href="{{ url_for('views.portScanner') }}"><i class="fa fa-arrow-right"></i></a>

                        </div>

                    </div>

                    <!-- <div class="col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="0.1s">

                        <div class="service-item d-flex flex-column text-center rounded">

                            <div class="service-icon flex-shrink-0">

                                <i class="fa-solid fa-triangle-exclamation fa-2x"></i>

                            </div>

                            <h5 class="mb-3">Vulnerability Scanner</h5>

                            <p class="m-0">A tool that detects known vulnerabilities, misconfigurations, and security weaknesses by scanning target systems and analyzing their configuration, software versions, and network services. 

                            </p>

                            <a class="btn btn-square" href="{{ url_for('views.vulnerabilityScanner') }}"><i class="fa fa-arrow-right"></i></a>

                        </div>

                    </div> -->

                </div>

            </div>

        </div>

        <!-- Service End -->





        



        <!-- Footer Start -->

        <div class="container-fluid bg-primary text-light footer wow fadeIn" data-wow-delay="0.1s">

            <div class="container py-5 px-lg-5">

                <div class="row g-5">

                    

                    <div class="col-md-6 col-lg-3">

                        <p class="section-title text-white h5 mb-4">Quick Link<span></span></p>

                        <a class="btn btn-link" href="{{ url_for('views.about') }}">About Us</a>

                        <a class="btn btn-link" href="{{ url_for('views.contact') }}">Contact Us</a>

                        <a class="btn btn-link" href="{{ url_for('views.policy') }}">Privacy Policy</a>

                        <a class="btn btn-link" href="{{ url_for('views.terms') }}">Terms & Condition</a>

                        

                    </div>

                    

                </div>

            </div>

            <div class="container px-lg-5">

                <div class="copyright">

                    <div class="row">

                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">

                               &copy; <a class="border-bottom" href="{{ url_for('views.index') }}">CyberFort</a>, All Rights Reserved.  

							

							

                    </div>

                </div>

            </div>

        </div>

        <!-- Footer End -->





        <!-- Back to Top -->

        <a href="#" class="btn btn-lg btn-secondary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

    </div>



    <!-- JavaScript Libraries -->

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

    <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>

    <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>

    <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>

    <script src="{{ url_for('static', filename='lib/counterup/counterup.min.js') }}"></script>

    <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>

    <script src="{{ url_for('static', filename='lib/isotope/isotope.pkgd.min.js') }}"></script>

    <script src="{{ url_for('static', filename='lib/lightbox/js/lightbox.min.js') }}"></script>



    <!-- Template Javascript -->

    <script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>



</html>